---
title: "Military Surplus"
---

This project looks at how much U.S. military surplus equipment has been transferred to law enforcement agencies. It uses data from from the "1033 program" handled through the [Law Enforcement Support Office](https://www.dla.mil/Disposition-Services/Offers/Law-Enforcement/Public-Information/), which posts data quarterly.

## Summary

Police departments across Central Texas, including Austin and San Marcos, have received millions of dollars in military-grade equipment since 2010, bringing surveillance tools, tactical robots and weapons accessories into local law enforcement.

The Austin Police Department alone received about $2.5 million in controlled equipment, including bomb disposal robots, surveillance robots and hundreds of weapon sights, illuminators and night vision devices. These tools expand the department’s ability to conduct tactical operations and surveillance using equipment originally designed for military use.

Smaller nearby agencies have also received significant transfers. The San Marcos Police Department, which serves a population of about 63,000, received nearly $3.2 million in military equipment, showing how even mid-size departments can obtain large amounts of federal surplus.

Across Texas, law enforcement agencies have received 18,677 controlled items since 2010, reflecting the continued flow of military resources into local policing at both large and small departments.

## Site link

Quarto website can be found [here](https://uswasaeed.github.io/military-surplus/).
